### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by SirXudes** [aria1th/litematica-printer#18]
Can there PLEASE be an install guide? People like me, with no knowledge, have 0 idea on how to do this.

**Comment by SirXudes** [comment]
Found out how to install finally after reading 100 other pages. Is there any way to get it for 1.16.5 or is it just 1.17

**Comment by aria1th** [comment]
there's 1.16.5 one (use 1.16.2 one), but not sure whether it works.
 use most recent litematica and malilib for 1.16 with it, I didn't really tested with 1.16. just compiled it.
