### ISSUE TITLE
Crash on joining world

### ISSUE THREAD

**Issue by Winsl0w** [aria1th/litematica-printer#37]
Game loads perfectly normally, however when joining a world it crashes immediately.

[crash-2022-05-11_00.19.13-client.txt](https://github.com/aria1th/litematica-printer/files/8665535/crash-2022-05-11_00.19.13-client.txt)

**Comment by aria1th** [comment]
very weird, since doEasyplaceAction is not being found for some reason. I just tested it with litematica 0.11.3, malilib 0.12.1 in 1.18.2 and it works correctly. seems your litematica is corrupted, can you update it?
