### ISSUE TITLE
Game crashes using  latest 19.3 printer

### ISSUE THREAD

**Issue by zepzoo** [aria1th/litematica-printer#42]
As title says game immediately crashes when I try to print.

**Comment by Cracken211** [comment]
" The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'java.util.List fi.dy.masa.litematica.schematic.placement.SchematicPlacementManager.getAllPlacementsTouchingChunk(net.minecraft.class_2338)' "
You got the same error?

**Comment by aria1th** [comment]
I fixed it in 1.19.2 branch, 1.19.3 (actually litematica) will be fixed soon.

**Comment by aria1th** [comment]
@zepzoo @JakeWallbets Check the latest release, and please reopen the issue if the crash continues!
