### ISSUE TITLE
@zepzoo @JakeWallbets Check the latest release, and please reopen the issue if the crash continues!

### ISSUE THREAD

**Issue by Cracken211** [aria1th/litematica-printer#43]
@zepzoo @JakeWallbets Check the latest release, and please reopen the issue if the crash continues!

_Originally posted by @aria1th in https://github.com/aria1th/litematica-printer/issues/42#issuecomment-1372045642_

**Comment by Cracken211** [comment]
The issue still persists on 1.19.2. Unsure if you really updated it I only see edits two weeks back or whatever it was.

**Comment by Cracken211** [comment]
I only see updates on 1.19.3 11 hours ago

**Comment by aria1th** [comment]
Yes, 1.19.2 version is fixed 2 weeks ago. The most recent litematica version is [ 4259743](https://www.curseforge.com/minecraft/mc-mods/litematica/files/4259743), I checked if printer works with this version. 

1.19.3 version is also fixed yesterday.
