### ISSUE TITLE
Crash when enter a world

### ISSUE THREAD

**Issue by Victito2brown** [aria1th/litematica-printer#45]
When I try to open my world this crash appears: "The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of fi.dy.masa.litematica.util.WorldUtils failed"
I have all installed perfectly and I tried deleting the "config" binder but it doesn't work.
Btw I use 1.17.1 version

**Comment by aria1th** [comment]
I released new version, so please check it!
(I suggest using multiconnect with latest minecraft version mods though)
