### ISSUE TITLE
Not able to print dirt path. 

### ISSUE THREAD

**Issue by zepzoo** [aria1th/litematica-printer#46]
No way to print dirt path?

**Comment by aria1th** [comment]
Dirt path itself... is not vanilla item, and unfortunately, printer cannot do actions that actually require player to 'look and use', such as waterlogging block after placement, pathing, stripping. Those actions will mess up 'fast placement', so I don't really plan to implement it...

**Comment by zepzoo** [comment]
alright rip, could be an on/off feature.

**Comment by aria1th** [comment]
@zepzoo Closes as https://github.com/aria1th/litematica-printer/actions/runs/4830207939
