### ISSUE TITLE
Some directional blocks get placed incorrectly in 1.19.4 pure vanilla server

### ISSUE THREAD

**Issue by Royalforce1** [aria1th/litematica-printer#51]
Hello, I've noticed that fake rotation doesn't seem to work on 1.19.4 vanilla servers (or in this case, realms), the upward and downward facing blocks seem to work fine, but the other directional blocks only work occasionally, and they usually just face the way the player faces. Here is the litematica schematic: 
[South_Cell1True.zip](https://github.com/aria1th/litematica-printer/files/11123679/South_Cell1True.zip)

**Comment by aria1th** [comment]
@Royalforce1 I confirmed issue in vanilla server too, seems like mojang changed something related to it. I'll try to fix it within 30 hour

**Comment by aria1th** [comment]
@Royalforce1 I tested again in 1.19.4 server environment (fabric) but cannot find any issue again... can you try increasing `printerFakeRotationTicks` and retry?

Also, you can try https://github.com/aria1th/litematica-printer/actions/runs/4579548317/jobs/8087438299 and option `printerSuppressLookPackets`, it should prevent any other direction packets while easyPlace is active.

**Comment by Royalforce1** [comment]
I turned up the rotation ticks, and used the modified .jar, but none of it seems to work (I also tried it on two different servers to make sure it wasn't just a specific server issue). I turned on the debugger and it kept saying that it had placed the blocks correctly, for example, it would "place" a block facing south, but in the actual game it's facing west, or some other direction. The blocks seem to get randomly turned around, they don't always face the way the player faces, but they also don't always face the way the litematica schematic tells it to. It might be important to point out that this is specifically happening with pistons and observers, I haven't tested with any other directional blocks. Also, it does appear to work on singleplayer for me.

**Comment by aria1th** [comment]
@Royalforce1 If `CarpetExtraFixedVersion` or `printerAccurateBlockPlacement` is on, can you turn off? Are you using other mods? 
when you enable `ShowExtraMessages`, it should tell you where player is facing. new feature should prevent all packets being sent via ClientPlayerEntity, which means at least all pistons should see some specific direction if you turn on easyplace.

You may join [discord](https://masa.dy.fi/discord) to leave some screenshots / video / etc if possible

**Comment by Royalforce1** [comment]
Those have both been off, I thought it might be other mods (I use freecam, which does some whacky stuff), but I removed every other non-essential mod and the issues still persist. I'll join the discord to try to provide some video or something too.

**Comment by aria1th** [comment]
@Royalforce1 I finally fixed it with #59
