### ISSUE TITLE
Direction is incorrect when placing blocks

### ISSUE THREAD

**Issue by hqqaazz** [aria1th/litematica-printer#59]
The printer always place blocks with wrong direction

tried to tweak something, with the following config it still happens:
printerFakeRotationAggressive:true
easyPlaceModePrinterMaxBlocks:1
easyPlaceModePrinterMaxItemChange:0
easyPlaceModeDelay:0.4
printerFakeRotationTicks:20

Following is an example if it helps

the correct direction in the schematic
![2023-06-22_11-06](https://github.com/aria1th/litematica-printer/assets/46392079/6d51304b-6d6a-48ff-9151-044a7c67845f)

the printer does the following :

place the closer block with the direction of the further one
![2023-06-22_11-07](https://github.com/aria1th/litematica-printer/assets/46392079/0a30845e-e468-4071-bb2b-2f76b0f31f52)

place the further block with the direction of the closer one

![2023-06-22_11-08](https://github.com/aria1th/litematica-printer/assets/46392079/33ce60bd-e813-4847-8638-95dc956f2669)

**Comment by hqqaazz** [comment]
though in the debug message the direction is correct, but the direction of placed block is correct

**Comment by aria1th** [comment]
I confirmed the directions are correct in vanilla / fabric servers, is it realm?

**Comment by hqqaazz** [comment]
is in 1.20.1 vanilla server
one more point is that the direction is correct in single player
just tested with printer only(fabric API + litematica + maliLib + this printer)

**Comment by aria1th** [comment]
@hqqaazz can you check if 'accurateBlockPlacement' is on? It should be off in server

**Comment by hqqaazz** [comment]
@aria1th the 'printerAccurateBlockPlacement' is off, and for the testing I am not using tweakeroo

**Comment by aria1th** [comment]
@hqqaazz can you check if it happens with default fake rotation setting? I'll check if something is wrong when I arrive home, but it seems like... placing at wrong float location :thinking:

**Comment by hqqaazz** [comment]
@aria1th I had reset all things in litematica settings and the direction is still incorrect

**Comment by hqqaazz** [comment]
![image](https://github.com/aria1th/litematica-printer/assets/46392079/9854eee2-7084-408c-8800-fe96c523b91c)
 this is the simple litematica I am using to test it

**Comment by aria1th** [comment]
@hqqaazz I confirmed the issue and released the fixed version!

**Comment by hqqaazz** [comment]
It's working now, thank you!
